const BlueCountryName = {
	ÅlandIslands: 'åland islands-blue',
	Albania: 'albania-blue',
	Algeria: 'algeria-blue',
	Andorra: 'andorra-blue',
	Armenia: 'armenia-blue',
	Austria: 'austria-blue',
	Azerbaijan: 'azerbaijan-blue',
	Belarus: 'belarus-blue',
	Belgium: 'belgium-blue',
	BosniaAndHerzegovina: 'bosnia and herzegovina-blue',
	Bulgaria: 'bulgaria-blue',
	Croatia: 'croatia-blue',
	Cyprus: 'cyprus-blue',
	CzechRepublic: 'czech republic-blue',
	Denmark: 'denmark-blue',
	Estonia: 'estonia-blue',
	FaroeIslands: 'faroe islands-blue',
	Finland: 'finland-blue',
	France: 'france-blue',
	Georgia: 'georgia-blue',
	Germany: 'germany-blue',
	Greece: 'greece-blue',
	Hungary: 'hungary-blue',
	Iceland: 'iceland-blue',
	Iran: 'iran-blue',
	Iraq: 'iraq-blue',
	Ireland: 'ireland-blue',
	Israel: 'israel-blue',
	Italy: 'italy-blue',
	Jordan: 'jordan-blue',
	Kazakhstan: 'kazakhstan-blue',
	Kosovo: 'kosovo-blue',
	Latvia: 'latvia-blue',
	Lebanon: 'lebanon-blue',
	Liechtenstein: 'liechtenstein-blue',
	Lithuania: 'lithuania-blue',
	Luxembourg: 'luxembourg-blue',
	Moldova: 'moldova-blue',
	Montenegro: 'montenegro-blue',
	Morocco: 'morocco-blue',
	Netherlands: 'netherlands-blue',
	NorthMacedonia: 'north macedonia-blue',
	Norway: 'norway-blue',
	Palestine: 'palestine-blue',
	Poland: 'poland-blue',
	Portugal: 'portugal-blue',
	Romania: 'romania-blue',
	Russia: 'russia-blue',
	SaudiArabia: 'saudi arabia-blue',
	Serbia: 'serbia-blue',
	Slovakia: 'slovakia-blue',
	Slovenia: 'slovenia-blue',
	Spain: 'spain-blue',
	Sweden: 'sweden-blue',
	Switzerland: 'switzerland-blue',
	Syria: 'syria-blue',
	Tunisia: 'tunisia-blue',
	Turkey: 'turkey-blue',
	Ukraine: 'ukraine-blue',
	UnitedKingdom: 'united kingdom-blue'
};

export default BlueCountryName;