const CountryName = {
	ÅlandIslands: 'åland islands',
	Albania: 'albania',
	Algeria: 'algeria',
	Andorra: 'andorra',
	Armenia: 'armenia',
	Austria: 'austria',
	Azerbaijan: 'azerbaijan',
	Belarus: 'belarus',
	Belgium: 'belgium',
	BosniaAndHerzegovina: 'bosnia and herzegovina',
	Bulgaria: 'bulgaria',
	Croatia: 'croatia',
	Cyprus: 'cyprus',
	CzechRepublic: 'czech republic',
	Denmark: 'denmark',
	Estonia: 'estonia',
	FaroeIslands: 'faroe islands',
	Finland: 'finland',
	France: 'france',
	Georgia: 'georgia',
	Germany: 'germany',
	Greece: 'greece',
	Hungary: 'hungary',
	Iceland: 'iceland',
	Iran: 'iran',
	Iraq: 'iraq',
	Ireland: 'ireland',
	Israel: 'israel',
	Italy: 'italy',
	Jordan: 'jordan',
	Kazakhstan: 'kazakhstan',
	Kosovo: 'kosovo',
	Latvia: 'latvia',
	Lebanon: 'lebanon',
	Liechtenstein: 'liechtenstein',
	Lithuania: 'lithuania',
	Luxembourg: 'luxembourg',
	Moldova: 'moldova',
	Montenegro: 'montenegro',
	Morocco: 'morocco',
	Netherlands: 'netherlands',
	NorthMacedonia: 'north macedonia',
	Norway: 'norway',
	Palestine: 'palestine',
	Poland: 'poland',
	Portugal: 'portugal',
	Romania: 'romania',
	Russia: 'russia',
	SaudiArabia: 'saudi arabia',
	Serbia: 'serbia',
	Slovakia: 'slovakia',
	Slovenia: 'slovenia',
	Spain: 'spain',
	Sweden: 'sweden',
	Switzerland: 'switzerland',
	Syria: 'syria',
	Tunisia: 'tunisia',
	Turkey: 'turkey',
	Ukraine: 'ukraine',
	UnitedKingdom: 'united kingdom'
};

export default CountryName;