import CountryName from "./CountryName.js";

const CountryHint = {
    ÅlandIslands: "A small island next to Finland...",
    Albania: "Rhymes with Romania...",
    Algeria: "In north Africa, it has a 'g' and 'a' in the word...",
    Andorra: "A small country between Spain and France...",
    Armenia: "In the Caucasus, ends with 'ia'...",
    Austria: "They speak German here...",
    Azerbaijan: "One of the few countries with the last letter of the alphabet in the name...",
    Belarus: "",
    Belgium: "French and Dutch are some of the national languages...",
    BosniaAndHerzegovina: "It has a unique name...",
    Bulgaria: "May or may not end with 'ia'...",
    Croatia: "Has a UNESCO site called Dubrovnik...",
    Cyprus: "An island below Turkey...",
    CzechRepublic: "Have you ever heard of Prague?",
    Denmark: "You may be understood if you speak Swedish...",
    Estonia: "It's not Lithuania...",
    FaroeIslands: "The only island colored blue...",
    Finland: "A Scandinavian country in the north...",
    France: "A big country that might speak ..ench",
    Georgia: "Could it be a state in the USA?",
    Germany: "Sprechen Sie Deutsch?",
    Greece: "Ever heard of Mykonos or Santorini?",
    Hungary: "I feel like I could eat right now...",
    Iceland: "A larger island with natural hot springs...",
    Iran: "I ...",
    Iraq: "I ...",
    Ireland: "It's NOT part of the UK",
    Israel: "A relatively new country in the bottom right of the map...",
    Italy: "I really do like canals...",
    Jordan: "This could be someone's name...",
    Kazakhstan: "It has a unique name...",
    Kosovo: "SO do you know now?",
    Latvia: "Ends in an 'a'...",
    Lebanon: "Non, it's this...",
    Liechtenstein: "A really small country between Switzerland and Austria...",
    Lithuania: "Well, it's NOT Latvia",
    Luxembourg: "You'd be surprised how many people don't about about this country...",
    Moldova: "",
    Montenegro: "Has a lot of montains...",
    Morocco: "A lot of the country is desert...",
    Netherlands: "Amsterdam is known as one of the most beautiful cities...",
    NorthMacedonia: "Well, it's not in the nor...",
    Norway: "Have you guessed this way before?",
    Palestine: "",
    Poland: "The countries flag consists of a white and red horizontal bar...",
    Portugal: "They don't speak Spanish...",
    Romania: "Hopefully you know about Bucharest, ......a",
    Russia: "The biggest landmass country in the world...",
    SaudiArabia: "Is very famous for their oil...",
    Serbia: "Used to be part of Yugoslavia, with a capital city of Belgrade...",
    Slovakia: "Not Slovenia...",
    Slovenia: "Not Slovakia...",
    Spain: "No, I'm not in pain...",
    Sweden: "People confused the gold of the flag with being yellow...",
    Switzerland: "Famous for it's mountains and chocolate...",
    Syria: "Sadly, war's caused significant damage to this country...",
    Tunisia: "Arabic and French are very commonly spoken languages...",
    Turkey: "This is usually served on Thanksgiving...",
    Ukraine: "Kiev is one of the oldest cities in Europe...",
    UnitedKingdom: "Comprised of 4 countries..."
};

export default CountryHint;