const GreenCountryName = {
	ÅlandIslands: 'åland islands-green',
	Albania: 'albania-green',
	Algeria: 'algeria-green',
	Andorra: 'andorra-green',
	Armenia: 'armenia-green',
	Austria: 'austria-green',
	Azerbaijan: 'azerbaijan-green',
	Belarus: 'belarus-green',
	Belgium: 'belgium-green',
	BosniaAndHerzegovina: 'bosnia and herzegovina-green',
	Bulgaria: 'bulgaria-green',
	Croatia: 'croatia-green',
	Cyprus: 'cyprus-green',
	CzechRepublic: 'czech republic-green',
	Denmark: 'denmark-green',
	Estonia: 'estonia-green',
	FaroeIslands: 'faroe islands-green',
	Finland: 'finland-green',
	France: 'france-green',
	Georgia: 'georgia-green',
	Germany: 'germany-green',
	Greece: 'greece-green',
	Hungary: 'hungary-green',
	Iceland: 'iceland-green',
	Iran: 'iran-green',
	Iraq: 'iraq-green',
	Ireland: 'ireland-green',
	Israel: 'israel-green',
	Italy: 'italy-green',
	Jordan: 'jordan-green',
	Kazakhstan: 'kazakhstan-green',
	Kosovo: 'kosovo-green',
	Latvia: 'latvia-green',
	Lebanon: 'lebanon-green',
	Liechtenstein: 'liechtenstein-green',
	Lithuania: 'lithuania-green',
	Luxembourg: 'luxembourg-green',
	Moldova: 'moldova-green',
	Montenegro: 'montenegro-green',
	Morocco: 'morocco-green',
	Netherlands: 'netherlands-green',
	NorthMacedonia: 'north macedonia-green',
	Norway: 'norway-green',
	Palestine: 'palestine-green',
	Poland: 'poland-green',
	Portugal: 'portugal-green',
	Romania: 'romania-green',
	Russia: 'russia-green',
	SaudiArabia: 'saudi arabia-green',
	Serbia: 'serbia-green',
	Slovakia: 'slovakia-green',
	Slovenia: 'slovenia-green',
	Spain: 'spain-green',
	Sweden: 'sweden-green',
	Switzerland: 'switzerland-green',
	Syria: 'syria-green',
	Tunisia: 'tunisia-green',
	Turkey: 'turkey-green',
	Ukraine: 'ukraine-green',
	UnitedKingdom: 'united kingdom-green'
};

export default GreenCountryName;