const RedCountryName = {
	ÅlandIslands: 'åland islands-red',
	Albania: 'albania-red',
	Algeria: 'algeria-red',
	Andorra: 'andorra-red',
	Armenia: 'armenia-red',
	Austria: 'austria-red',
	Azerbaijan: 'azerbaijan-red',
	Belarus: 'belarus-red',
	Belgium: 'belgium-red',
	BosniaAndHerzegovina: 'bosnia and herzegovina-red',
	Bulgaria: 'bulgaria-red',
	Croatia: 'croatia-red',
	Cyprus: 'cyprus-red',
	CzechRepublic: 'czech republic-red',
	Denmark: 'denmark-red',
	Estonia: 'estonia-red',
	FaroeIslands: 'faroe islands-red',
	Finland: 'finland-red',
	France: 'france-red',
	Georgia: 'georgia-red',
	Germany: 'germany-red',
	Greece: 'greece-red',
	Hungary: 'hungary-red',
	Iceland: 'iceland-red',
	Iran: 'iran-red',
	Iraq: 'iraq-red',
	Ireland: 'ireland-red',
	Israel: 'israel-red',
	Italy: 'italy-red',
	Jordan: 'jordan-red',
	Kazakhstan: 'kazakhstan-red',
	Kosovo: 'kosovo-red',
	Latvia: 'latvia-red',
	Lebanon: 'lebanon-red',
	Liechtenstein: 'liechtenstein-red',
	Lithuania: 'lithuania-red',
	Luxembourg: 'luxembourg-red',
	Moldova: 'moldova-red',
	Montenegro: 'montenegro-red',
	Morocco: 'morocco-red',
	Netherlands: 'netherlands-red',
	NorthMacedonia: 'north macedonia-red',
	Norway: 'norway-red',
	Palestine: 'palestine-red',
	Poland: 'poland-red',
	Portugal: 'portugal-red',
	Romania: 'romania-red',
	Russia: 'russia-red',
	SaudiArabia: 'saudi arabia-red',
	Serbia: 'serbia-red',
	Slovakia: 'slovakia-red',
	Slovenia: 'slovenia-red',
	Spain: 'spain-red',
	Sweden: 'sweden-red',
	Switzerland: 'switzerland-red',
	Syria: 'syria-red',
	Tunisia: 'tunisia-red',
	Turkey: 'turkey-red',
	Ukraine: 'ukraine-red',
	UnitedKingdom: 'united kingdom-red'
};

export default RedCountryName;